export const reasonsBackOrder = [
    { id: 1, title: 'All Backorders' },
    { id: 2, title: 'With Reason' },
    { id: 3, title: 'Without Reason' },
    { id: 4, title: 'SERIE / OVERSCHEDULED' },
    { id: 5, title: 'SERIE / DOWNTIME' },
    { id: 6, title: 'GLASS / BROKEN' },
    { id: 7, title: 'GLASS / INCORRECT OPTION' },
    { id: 8, title: 'GLASS / DID NOT ARRIVE' },
    { id: 9, title: 'HARDWARE / BROKEN' },
    { id: 10, title: 'HARDWARE / INCORRECT OPTION' },
    { id: 11, title: 'HARDWARE / DID NOT ARRIVE' },
    { id: 12, title: 'INT GLASS / BROKEN' },
    { id: 13, title: 'INT GLASS / INCORRECT OPTION' },
    { id: 14, title: 'INT GLASS / DID NOT ARRIVE' },
    { id: 15, title: 'MATERIAL / DAMAGE' },
    { id: 16, title: 'MATERIAL / OUT OF MATERIAL' },
    { id: 17, title: 'SCREEN' },
    { id: 18, title: 'SDL / BROKEN' },
    { id: 19, title: 'SDL / INCORRECT OPTION' },
    { id: 20, title: 'SDL / DID NOT ARRIVE' },
    { id: 21, title: 'SHAPE / BROKEN' },
    { id: 22, title: 'SHAPE / INCORRECT OPTION' },
    { id: 23, title: 'SHAPE / DID NOT ARRIVE' },
    { id: 24, title: 'ORDER / INVALID MODEL' },
    { id: 25, title: 'OTHER / X ' },
];
